export const anatomyEntities = [
  {
    id: "uterus",
    name: "Útero",
    latinName: "Uterus",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "organ",
    description: "Órgão muscular oco, em formato de pera invertida, responsável por abrigar e nutrir o embrião/feto durante a gestação.",
    relatedStructures: ["cervix", "fallopian_tube", "ovary", "vagina", "broad_ligament", "round_ligament"],
    arterialSupply: ["uterine_artery", "ovarian_artery"],
    venousDrainage: ["uterine_vein", "ovarian_vein"],
    innervation: ["uterovaginal_plexus"],
    histology: ["endometrium", "myometrium", "perimetrium"],
    embryology: ["ductos_de_muller", "mesoderma_intermediario"],
    pathologies: ["miomatose", "adenomiose", "endometriose", "carcinoma_endometrial"],
    markerIds: ["marker-1"],
    clinicalRelevance: ["Sítio de implantação embrionária", "Órgão alvo de histerectomias por sangramento anormal"],
    commonQuestions: ["Qual a irrigação do útero?", "Quais as camadas histológicas do útero?"],
    examPearls: ["Artéria uterina passa sobre o ureter ('água sob a ponte') durante histerectomia."],
    relatedPathologies: ["Leiomioma (Miomatose)", "Hiperplasia Endometrial"]
  },
  {
    id: "ovary",
    name: "Ovário",
    latinName: "Ovarium",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "organ",
    description: "Gônada feminina responsável pela gametogênese (óvulos) e produção de hormônios esteróides (estrogênio e progesterona).",
    relatedStructures: ["fallopian_tube", "uterus", "ovarian_ligament", "broad_ligament"],
    arterialSupply: ["ovarian_artery"],
    venousDrainage: ["ovarian_vein"],
    innervation: ["ovarian_plexus"],
    histology: ["cortex_ovariano", "medula_ovariana", "foliculos_ovarianos"],
    embryology: ["crista_gonadal"],
    pathologies: ["cisto_ovariano", "sop", "carcinoma_ovariano"],
    markerIds: ["marker-ovary-1"],
    clinicalRelevance: ["Produção endócrina vital", "Avaliação ultrassonográfica de folículos"],
    commonQuestions: ["O que devo saber para prova sobre ovário?", "Qual a drenagem venosa do ovário direito vs esquerdo?"],
    examPearls: ["A veia ovariana direita drena na VCI; a esquerda drena na veia renal esquerda."],
    relatedPathologies: ["Síndrome dos Ovários Policísticos (SOP)", "Tumor Epitelial Ovariano"]
  },
  {
    id: "fallopian_tube",
    name: "Tuba Uterina",
    latinName: "Tuba uterina",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "organ",
    description: "Estruturas tubulares que conectam os ovários ao útero. Local principal onde ocorre a fertilização.",
    relatedStructures: ["ovary", "uterus", "broad_ligament"],
    arterialSupply: ["ovarian_artery", "uterine_artery"],
    venousDrainage: ["ovarian_vein", "uterine_vein"],
    innervation: ["ovarian_plexus", "uterovaginal_plexus"],
    histology: ["mucosa_ciliada", "camada_muscular", "serosa"],
    embryology: ["ductos_de_muller"],
    pathologies: ["salpingite", "gravidez_ectopica", "doenca_inflamatoria_pelvica"],
    markerIds: ["marker-tube-1"],
    clinicalRelevance: ["Lugar mais comum de gravidez ectópica (porção ampolar).", "Bloqueio tubário é causa de infertilidade."],
    commonQuestions: ["Quais as partes da tuba uterina?", "Onde ocorre a fertilização?"],
    examPearls: ["Porção ampolar é a mais larga e onde ocorre a fertilização. Porção ístmica é a mais estreita."],
    relatedPathologies: ["Gravidez Ectópica Tubária", "DIP"]
  },
  {
    id: "cervix",
    name: "Colo Uterino",
    latinName: "Cervix uteri",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "organ_part",
    description: "Porção inferior e estreita do útero que faz a transição cilíndrica até o canal vaginal.",
    relatedStructures: ["uterus", "vagina"],
    arterialSupply: ["uterine_artery", "vaginal_artery"],
    venousDrainage: ["uterine_vein"],
    innervation: ["uterovaginal_plexus"],
    histology: ["endocervice", "ectocervice", "zona_de_transformacao"],
    embryology: ["ductos_de_muller"],
    pathologies: ["hpv", "nic", "carcinoma_cervical", "cervicite"],
    markerIds: ["marker-2"],
    clinicalRelevance: ["Sítio principal de infecção persistente por HPV", "Alvo principal do Papanicolau."],
    commonQuestions: ["Mostre estruturas relacionadas ao colo uterino.", "O que é a zona de transformação?"],
    examPearls: ["Junção escamocolunar (JEC) é o local primário de desenvolvimento do câncer cervical."],
    relatedPathologies: ["Neoplasia Intraepitelial Cervical (NIC)", "Cervicite"]
  },
  {
    id: "endometrium",
    name: "Endométrio",
    latinName: "Endometrium",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "tissue",
    description: "Camada mucosa interna do útero que descama durante a menstruação e espessa para a implantação.",
    relatedStructures: ["myometrium", "cervix"],
    arterialSupply: ["arterias_espiraladas", "arterias_basais"],
    venousDrainage: ["uterine_vein"],
    innervation: ["uterovaginal_plexus"],
    histology: ["epitelio_colunar_simples", "glandulas_endometriais"],
    embryology: ["ductos_de_muller"],
    pathologies: ["endometriose", "hiperplasia_endometrial", "carcinoma_endometrial"],
    markerIds: ["marker-endometrium"],
    clinicalRelevance: ["A camada funcional responde a hormônios ovarianos", "Espessamento anormal pode indicar patologia."],
    commonQuestions: ["Quais patologias se relacionam com o endométrio?", "O endométrio possui quantas subcamadas?"],
    examPearls: ["Apenas a camada funcional (basal e esponjosa superficial) descama na menstruação."],
    relatedPathologies: ["Endometriose", "Carcinoma Endometrial"]
  },
  {
    id: "myometrium",
    name: "Miométrio",
    latinName: "Myometrium",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "tissue",
    description: "Camada muscular espessa do útero responsável pelas contrações no parto e menstruação.",
    relatedStructures: ["endometrium", "perimetrium"],
    arterialSupply: ["arterias_arqueadas"],
    venousDrainage: ["plexo_venoso_uterino"],
    innervation: ["uterovaginal_plexus"],
    histology: ["musculo_liso", "tecido_conjuntivo"],
    embryology: ["mesenquima_esplancnico"],
    pathologies: ["miomatose", "adenomiose", "leiomiossarcoma"],
    markerIds: ["marker-myometrium"],
    clinicalRelevance: ["Crescimento benigno focal origina leiomiomas.", "Invasão endometrial no miométrio caracteriza adenomiose."],
    commonQuestions: ["O que é adenomiose?", "Qual a irrigação principal do miométrio?"],
    examPearls: ["As fibras musculares uterinas em 'figura de 8' espremem os vasos para evitar hemorragia pós-parto."],
    relatedPathologies: ["Leiomioma", "Adenomiose"]
  },
  {
    id: "uterine_artery",
    name: "Artéria Uterina",
    latinName: "Arteria uterina",
    system: "Sistema Cardiovascular",
    layer: "arterial",
    category: "blood_vessel",
    description: "Principal suprimento sanguíneo arterial para o útero. Ramo da artéria ilíaca interna.",
    relatedStructures: ["uterus", "cervix", "fallopian_tube"],
    arterialSupply: [],
    venousDrainage: [],
    innervation: [],
    histology: ["endotelio", "tunica_media", "tunica_adventicia"],
    embryology: ["arcos_aorticos"],
    pathologies: ["aneurisma", "estenose"],
    markerIds: ["marker-art-uterina"],
    clinicalRelevance: ["Pode ser embolizada para tratamento de miomas.", "Sua laqueadura ajuda a controlar hemorragia pós-parto."],
    commonQuestions: ["De onde se origina a artéria uterina?", "Qual a relação com o ureter?"],
    examPearls: ["Cruza anterior ao ureter próximo ao colo do útero ('água passa sob a ponte')."],
    relatedPathologies: ["Hemorragia Uterina Anormal"]
  },
  {
    id: "uterine_vein",
    name: "Veia Uterina",
    latinName: "Vena uterina",
    system: "Sistema Cardiovascular",
    layer: "venous",
    category: "blood_vessel",
    description: "Drenagem venosa principal do útero que deságua na veia ilíaca interna.",
    relatedStructures: ["uterus", "cervix"],
    arterialSupply: [],
    venousDrainage: [],
    innervation: [],
    histology: ["endotelio", "valvulas_venosas"],
    embryology: ["veias_cardinais"],
    pathologies: ["trombose_venosa_pelvica", "varizes_pelvicas"],
    markerIds: ["marker-vein-uterina"],
    clinicalRelevance: ["Forma um plexo venoso ao redor do colo.", "Varizes pélvicas geram dor crônica."],
    commonQuestions: ["Para onde drena a veia uterina?"],
    examPearls: ["Drena o plexo uterino e desemboca primariamente na veia ilíaca interna."],
    relatedPathologies: ["Síndrome de Congestão Pélvica"]
  },
  {
    id: "vagina",
    name: "Vagina",
    latinName: "Vagina",
    system: "Sistema Reprodutor Feminino",
    layer: "organ",
    category: "organ",
    description: "Tubo fibromuscular que se estende do colo uterino até o vestíbulo vaginal.",
    relatedStructures: ["cervix", "uterus"],
    arterialSupply: ["vaginal_artery", "pudendal_artery"],
    venousDrainage: ["vaginal_vein"],
    innervation: ["pudendal_nerve", "uterovaginal_plexus"],
    histology: ["epitelio_escamoso_estratificado_nao_queratinizado"],
    embryology: ["seio_urogenital", "ductos_de_muller"],
    pathologies: ["vaginite", "vaginose_bacteriana", "prolapso_vaginal"],
    markerIds: ["marker-vagina"],
    clinicalRelevance: ["Canal do parto", "Órgão copulador feminino", "Via de exame especular."],
    commonQuestions: ["Qual a inervação da vagina?", "O que é fórnice vaginal?"],
    examPearls: ["A inervação do 1/3 inferior é somática (nervo pudendo), sensível à dor, 2/3 superiores são viscerais."],
    relatedPathologies: ["Candidiase", "Trichomoníase", "Vaginose"]
  },
  {
    id: "broad_ligament",
    name: "Ligamento Largo",
    latinName: "Ligamentum latum uteri",
    system: "Sistema Reprodutor Feminino",
    layer: "ligament",
    category: "ligament",
    description: "Prega peritoneal dupla que se estende das bordas laterais do útero às paredes laterais da pelve.",
    relatedStructures: ["uterus", "fallopian_tube", "ovary"],
    arterialSupply: ["uterine_artery", "ovarian_artery"],
    venousDrainage: ["uterine_vein", "ovarian_vein"],
    innervation: [],
    histology: ["mesotelio", "tecido_conjuntivo"],
    embryology: ["peritonio"],
    pathologies: ["cisto_paraooforico"],
    markerIds: ["marker-broad-ligament"],
    clinicalRelevance: ["Contém artérias uterinas, ovários, tubas e nervos."],
    commonQuestions: ["O que o ligamento largo envolve?", "Quais as divisões do ligamento largo?"],
    examPearls: ["Divide-se em mesométrio (útero), mesossalpinge (tuba) e mesovário (ovário)."],
    relatedPathologies: ["Cisto de Gartner"]
  },
  {
    id: "round_ligament",
    name: "Ligamento Redondo",
    latinName: "Ligamentum teres uteri",
    system: "Sistema Reprodutor Feminino",
    layer: "ligament",
    category: "ligament",
    description: "Fibromuscular, passa pelo canal inguinal e se insere nos grandes lábios. Mantém a anteversão uterina.",
    relatedStructures: ["uterus", "labia_majora"],
    arterialSupply: ["sampson_artery"],
    venousDrainage: [],
    innervation: [],
    histology: ["musculo_liso", "tecido_conjuntivo"],
    embryology: ["gubernaculum"],
    pathologies: ["dor_no_ligamento_redondo_na_gravidez"],
    markerIds: ["marker-round-ligament"],
    clinicalRelevance: ["Estira-se durante a gravidez, causando dor pélvica comum (dor do ligamento redondo)."],
    commonQuestions: ["Qual a função do ligamento redondo?", "Onde ele se insere?"],
    examPearls: ["É homólogo ao gubernáculo testicular masculino."],
    relatedPathologies: ["Dor gestacional"]
  },
  {
    id: "ovarian_ligament",
    name: "Ligamento Útero-ovariano",
    latinName: "Ligamentum ovarii proprium",
    system: "Sistema Reprodutor Feminino",
    layer: "ligament",
    category: "ligament",
    description: "Cordão fibroso que conecta o pólo inferior do ovário ao corno uterino.",
    relatedStructures: ["ovary", "uterus"],
    arterialSupply: ["ovarian_artery_branches"],
    venousDrainage: [],
    innervation: [],
    histology: ["tecido_conjuntivo", "musculo_liso"],
    embryology: ["gubernaculum"],
    pathologies: [],
    markerIds: ["marker-ovarian-ligament"],
    clinicalRelevance: ["Marco anatômico na histerectomia e ooforectomia."],
    commonQuestions: ["Qual a diferença entre ligamento suspensor do ovário e útero-ovariano?"],
    examPearls: ["Não confundir com ligamento suspensor do ovário (infundibulopélvico), que carrega os vasos ovarianos."],
    relatedPathologies: ["Torção ovariana (junto com suspensor)"]
  }
];
